
# docker-compose.yml
version: '3.8'
services:
  core_api:
    build: .
    container_name: "cartoon-api-container"
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000